name: Test Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test Electron App (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-22.04, macos-13]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          yarn --skip-integrity-check --network-timeout 100000
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          yarn build:dev
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          yarn lint
        
      - name: Test (Linux)
        if: matrix.os == 'ubuntu-22.04'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn electron test
          
      - name: Test (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          yarn electron test
          
      - name: Test (macOS)
        if: matrix.os == 'macos-13'
        run: |
          yarn electron test 